apiVersion: v1
kind: Pod
metadata:
  name: employee-cert-pod
  namespace: sales
  labels: 
    app: employee-cert-label
    type: employee-cert-service
spec:
  containers:
    - name: employee-cert-pod
      image: aksbyexampleacr.azurecr.us/employee-cert:1.0-amd64
      ports:
      - containerPort: 9000


 
        